# NumPy Exercises for Linear Algebra

The goal of the numpy exercises is to serve as a reference as well as to get you to apply numpy beyond the basics.

All the codes here are adapted from https://www.machinelearningplus.com/python/101-numpy-exercises-python/.

## 1. Import numpy as np and see the version

In [10]:
import numpy as np
print(np.__version__)

1.21.2


## 2. How to create a 1D array?

In [11]:
# array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 3. How to create a boolean array?

In [12]:
np.full((3, 3), True, dtype=bool)

# or 

np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## 4. How to extract items that satisfy a given condition from 1D array?

In [13]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#> array([1, 3, 5, 7, 9])
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

## 5. How to replace items that satisfy a condition with another value in numpy array?

In [14]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## 6. How to replace items that satisfy a condition without affecting the original array?

In [37]:
arr = np.arange(10)

out = np.where(arr % 2 == 1, -1, arr)

print(out)
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


## 7. How to reshape an array?

In [18]:
arr = np.arange(10)

#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])

arr.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 8. How to stack two arrays vertically?

In [20]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])

# Method 1:
np.concatenate([a, b], axis=0)

# Method 2:
np.vstack([a, b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## 9. How to stack two arrays horizontally?

In [21]:
a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)

#> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#>        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

# Method 1:
np.concatenate([a, b], axis=1)

# Method 2:
np.hstack([a, b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## 10. How to get the positions where elements of two arrays match?

In [26]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

#> (array([1, 3, 5, 7]),)

np.where(a == b)

(array([1, 3, 5, 7]),)

## 11. How to extract all numbers between a given range from a numpy array?

In [27]:
a = np.arange(15)

# all the the elements between 5 and 10

# Method 1
index = np.where((a >= 5) & (a <= 10))
a[index]

# Method 2:
index = np.where(np.logical_and(a>=5, a<=10))
a[index]
#> (array([6, 9, 10]),)

# Method 3: (thanks loganzk!)
a[(a >= 5) & (a <= 10)]

array([ 5,  6,  7,  8,  9, 10])

## 12. How to swap two columns in a 2d numpy array?

In [28]:
arr = np.arange(9).reshape(3,3)

arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

## 13. How to reverse the rows of a 2D array?

In [29]:
arr = np.arange(9).reshape(3,3)

arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

## 14. How to create a 2D array containing random floats between 5 and 10?

In [31]:
rand_arr = np.random.uniform(5,10, size=(5,3))
rand_arr

array([[7.78170343, 9.11672146, 8.41021512],
       [6.71068466, 9.94250475, 6.02890184],
       [8.32608165, 5.71324489, 9.57377517],
       [8.60605259, 6.18753242, 9.7657579 ],
       [7.10606099, 8.0569374 , 6.77717168]])