# Introduction to NumPy

### NumPy: A Python Library for Scientific Computing


The reference material for this notebook can be found in the [NumPy documentation](https://numpy.org/doc/stable/user/quickstart.html).

In [1]:
# import numpy library
import numpy as np

## The Basics

NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers. In NumPy dimensions are called **axes**.

For example, the coordinates of a point in 3D space [1, 2, 1] has one axis. That axis has 3 elements in it, so we say it has a length of 3. In the example pictured below, the array has 2 axes. The first axis has a length of 2, the second axis has a length of 3.

In [2]:
# create a sample numpy array
np.array([[1, 0, 0],
          [0, 1, 2]])

array([[1, 0, 0],
       [0, 1, 2]])

In [4]:
# create a 3x5 numpy array with values in [0, 14]
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
# create a numpy array of squares of numbers in the range of [0, 10)
squares = np.array([x**2 for x in range(10)])
squares

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [7]:
# see the type of the `squares` numpy array
type(squares) 

numpy.ndarray

NumPy’s array class is called ndarray. It is also known by the alias array. **Note that numpy.array is not the same as the Standard Python Library class array.array**, which only handles one-dimensional arrays and offers less functionality. The more important attributes of an ndarray object are:

In [9]:
# some of the useful np.array attributes

# 1. the dimensions of the array.
a.shape
# 2. the number of axes (dimensions) of the array.
a.ndim
# 3. the total number of elements of the array
a.size
# 4. an object describing the type of the elements in the array.
a.dtype

dtype('int64')

## Array Creation
There are several ways to create arrays.

For example, you can create an array from a regular Python list or tuple using the array function. The type of the resulting array is deduced from the type of the elements in the sequences.

In [ ]:
# create a numpy array from a python list
a = np.array([2, 3, 4])
# create a numpy array from a python list using loops
squares = [x**3 for x in range(10)]

In [16]:
# python list -> numpy array
squares = [x**2 for x in range(10)]
# python tuple -> numpy array
cubes = tuple(x**3 for x in range(10))
# python set -> numpy array
evens = {x for x in range(10) if x%2 == 0}  

print(type(squares))
print(type(cubes))
print(type(evens))

print(squares)
print(cubes)
print(evens)

<class 'list'>
<class 'tuple'>
<class 'set'>
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
(0, 1, 8, 27, 64, 125, 216, 343, 512, 729)
{0, 2, 4, 6, 8}


In [18]:
# now, lets transform them to numpy arrays
a = np.array(squares)
b = np.array(cubes)
c = np.array(evens)

print(a)
print(b)
print(c)

[ 0  1  4  9 16 25 36 49 64 81]
[  0   1   8  27  64 125 216 343 512 729]
{0, 2, 4, 6, 8}


In [25]:
# create array from nested lists of depth 2
seq1 = [[x, x**2, x**3] for x in range(10)]

a = np.array(seq1)
print(a)
print(a.ndim)

[[  0   0   0]
 [  1   1   1]
 [  2   4   8]
 [  3   9  27]
 [  4  16  64]
 [  5  25 125]
 [  6  36 216]
 [  7  49 343]
 [  8  64 512]
 [  9  81 729]]
2


In [29]:
# create a 3x3 arrary of 0's
zeros = np.zeros((3, 3), dtype=np.int32)
# create a 2x2 array of 1's
ones = np.ones((2, 2), dtype=np.int32)

print(zeros, zeros.dtype.name)
print(ones, ones.dtype.name)

[[0 0 0]
 [0 0 0]
 [0 0 0]] int32
[[1 1]
 [1 1]] int32


In [30]:
# create an array from range [5, 30] with step of 5
np.arange(5, 30, 5)

array([ 5, 10, 15, 20, 25])

In [32]:
# create array of 100 values between 0 and 1
np.linspace(0, 1, 100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [36]:
# create an array from a function

def f(row_num, col_num):
    return 2*row_num + col_num

F = np.fromfunction(f, (3, 3), dtype=int)
F

array([[0, 1, 2],
       [2, 3, 4],
       [4, 5, 6]])

## Printing Array

When you print an array, NumPy displays it in a similar way to nested lists, but with the following layout:

1. the last axis is printed from left to right,
2. the second-to-last is printed from top to bottom,
3. the rest are also printed from top to bottom, with each slice separated from the next by an empty line.

One-dimensional arrays are then printed as rows, bidimensionals as matrices and tridimensionals as lists of matrices.

In [37]:
dim1 = np.arange(15)                   # Create 1 1x15 matrix;  n=1
dim2 = np.arange(15).reshape(3, 5)     # Create 1 3x5 matrix;   n=2
dim3 = np.arange(24).reshape(2, 3, 4)  # Create 2 3x4 matrices; n=3

print(dim1, end='\t[1x15]\n\n')
print(dim2, end='\t[3x5]\n\n')
print(dim3, end='\t[2x3x4]')

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]	[1x15]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]	[3x5]

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]	[2x3x4]

## Basic Operations

Arithmetic operators on arrays apply *elementwise*. A new array is created and filled with the result.

In [45]:
# let a be the array of numbers in the range of [0, 10)
a = np.arange(10)
# let b an array of 2's with the length of 10
b = 2 * np.ones((10,))
# now subtract b from a 

result = a - b
result

array([-2., -1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.])

In [46]:
result < 0

array([ True,  True, False, False, False, False, False, False, False,
       False])

In [47]:
# element-wise multipication
a = np.ones(15).reshape(3, 5)
b = np.ones(15).reshape(5, 3)

mult = a * 10            # element-wise multiplication
dot_prod1 = a.dot(b)     # dot product version 1
dot_prod2 = np.dot(a, b) # dot product version 2

print(mult, end='\n\n')
print(dot_prod1, end='\n\n')
print(dot_prod2)

[[10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]]

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


In [48]:
# useful array methods

a = np.arange(1, 11)

print('Sum:', a.sum())
print('Min:', a.min())
print('Max:', a.max())

Sum: 55
Min: 1
Max: 10


In [49]:
# applying methods to a single axis
a = np.arange(15).reshape(3, 5) + 1

# sum of each column
print(a.sum(axis=0)) 
# min of each row
print(a.min(axis=1)) 
a

[18 21 24 27 30]
[ 1  6 11]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

## Universal Functions
NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions” (ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

In [52]:
from numpy import pi

# universal functions (sin, cos, exp, sqrt, ... etc)


a = np.linspace(0, 2*pi, 10000)

sin_a = np.sin(a)
sqrt_a = np.sqrt(a)
exp_a = np.exp(a)

print(sin_a, end='\n\n')
print(sqrt_a, end='\n\n')
print(exp_a, end='\n\n')

[ 0.00000000e+00  6.28381328e-04  1.25676241e-03 ... -1.25676241e-03
 -6.28381328e-04 -2.44929360e-16]

[0.         0.02506754 0.03545085 ... 2.50637757 2.50650293 2.50662827]

[  1.           1.00062858   1.00125755 ... 534.81909228 535.15526825
 535.49165552]



## Indexing, slicing and iterating

In [55]:
# indexing elements from multidimentional arrays

a = np.array([x**2 for x in range(1, 11)]).reshape(2, 5)

print (a)
# get the first row
print(a[0])
# get the last element
print(a[-1])
# get the (i,j)th element
print(a[0][0])

[[  1   4   9  16  25]
 [ 36  49  64  81 100]]
[ 1  4  9 16 25]
[ 36  49  64  81 100]
1


In [56]:
# slicing numpy arrays
cubes = np.arange(1, 13).reshape(4, 3)**3

# all rows all columns
print(cubes[:, :])
# first col
print(cubes[:, 0])
# first row
print(cubes[0, :])

[[   1    8   27]
 [  64  125  216]
 [ 343  512  729]
 [1000 1331 1728]]
[   1   64  343 1000]
[ 1  8 27]


In [57]:
# iterating through arrays elements
a = np.array([x+1 for x in range(10)])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
for element in a:
    print(element, end=', ')
        

1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 

In [62]:
# flatting a 5x5x5 array for iterating
for el in a.flat:
    print(el, end=', ')

1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 

## Shape Manipulation
Changing the shape of an array.

An array has a shape given by the number of elements along each axis:

In [66]:
# create a random array of shape 3x4
a = np.floor(10*np.random.random((3, 4)))
a

array([[5., 6., 6., 9.],
       [4., 1., 4., 9.],
       [0., 1., 1., 1.]])

In [67]:
# return a copy of the array flattened
a.ravel()

array([5., 6., 6., 9., 4., 1., 4., 9., 0., 1., 1., 1.])

In [68]:
# change the shape of the array to a 2x6 matrix
a.reshape(6, 2)

array([[5., 6.],
       [6., 9.],
       [4., 1.],
       [4., 9.],
       [0., 1.],
       [1., 1.]])

In [69]:
# ge the tarnsposed of the existing array
a.T

array([[5., 4., 0.],
       [6., 1., 1.],
       [6., 4., 1.],
       [9., 9., 1.]])

## Stacking NumPy arrays horizantally and vertically

Several arrays can be stacked together along different axes:

In [70]:
# create a 3x3 array of 0's
a = np.zeros(9, dtype=int).reshape(3, 3)
# create a 3x3 array of 1's
b = np.ones(9, dtype=int).reshape(3, 3)

# stack a and b horizantally
hor = np.hstack((a, b))
hor


array([[0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1]])

In [73]:
# stack a and b vertically
ver = np.vstack((a, b))
ver

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [75]:
# similarly, row_stack and comlumn stack can be used to stack into 2D arrays
r_stack = np.row_stack((a, b))
c_stack = np.column_stack((a, b))


# check if the row_stack and np.vstack are similar
np.row_stack is np.vstack

True

## Splitting one array into several smaller ones
Using *hsplit*, you can split an array along its horizontal axis, either by specifying the number of equally shaped arrays to return, or by specifying the columns after which the division should occur:

In [78]:
# use hsplit or vsplit
a = np.ones(9).reshape(3, 3)

a_1, a_2, a_3 = np.hsplit(a, 3)
print(a, end='\n\n')
print(a_1, end='\n\n')
print(a_2, end='\n\n')
print(a_3, end='\n\n')

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[1.]
 [1.]
 [1.]]

[[1.]
 [1.]
 [1.]]

[[1.]
 [1.]
 [1.]]

